<?php

namespace App\Jobs;

use App\Models\EmployeeAttendance;
use App\Models\EmployeeAttendanceStatusLog;
use App\Models\EmployeeLeaveAchieveLog;
use App\Models\EmployeeOfficialInformation;
use App\Models\Holiday;
use App\Models\Shift;
use Carbon\Carbon;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

/**
 * ProcessSandwichedHolidaysJob
 *
 * Two independent rules are applied per employee, per month (with a buffer
 * window so chains that cross a month boundary are still detected):
 *
 * Rule 1 - Sandwiched holiday/weekend:
 *   If a holiday (any holiday_type_id, including weekends) has an absent
 *   working day immediately before it and an absent working day immediately
 *   after it (skipping over any other holidays that are themselves part of
 *   the same sandwiched chain), the holiday becomes an absent day for that
 *   employee and its holidays-table row is deleted.
 *
 * Rule 2 - Full work-week absent -> trailing weekend absent:
 *   For each of an employee's weekend blocks (one or more consecutive dates
 *   with holiday_type_id=8), look at the work-week immediately before it -
 *   i.e. every non-holiday day between the end of the previous weekend block
 *   (exclusive) and the start of this weekend block (exclusive). Days that
 *   are holidays (not weekend, not absent) are skipped when checking; only
 *   the actual working days are examined. If every one of those working
 *   days is Absent, the whole weekend block becomes absent and its
 *   holidays-table rows are deleted. This rule only looks backward (the
 *   week before the weekend), never forward.
 *
 * In both rules, if the employee actually worked (Present) on a would-be
 * absent weekend/holiday day (weekend duty), that day is left untouched.
 *
 * When a day becomes absent:
 * 1. Its holidays-table row(s) are deleted.
 * 2. Any existing attendance/status-log/leave-achieve-log rows for that date
 *    are deleted.
 * 3. A minimal employee_attendance row is inserted (no punches, no shift
 *    calculation) together with an employee_attendance_status_logs row
 *    carrying attendance_status = 0 (Absent), and absent_bridge = 1 so
 *    these rows are identifiable as generated by this job. This does NOT
 *    go through AttendanceProcessingService - that service is built around
 *    a fully eager-loaded punch-processing row (e.g. employeeAttendanceTemps)
 *    from the normal attendance pipeline and is not meant to be driven with
 *    a synthetic row for a day that has no punches at all.
 *
 * A day's Present/Absent status is read from employee_attendance_status_logs
 * .attendance_status (0 = Absent, 1 = Present) - employee_attendance itself
 * has no attendance_status column.
 */
class ProcessSandwichedHolidaysJob extends Job implements ShouldQueue
{
    use InteractsWithQueue, Queueable, SerializesModels;

    protected array $payload;
    protected int $systemUserId;

    private const WEEKEND_HOLIDAY_TYPE_ID = 8;
    private const PRESENT_STATUS_CODE = 1;
    private const ABSENT_STATUS_CODE = 0;

    /**
     * @param array $payload
     *   - year: int (default: previous month year)
     *   - month: int (default: previous month)
     *   - employee_user_ids: array|null (optional, specific employees)
     */
    public function __construct(array $payload)
    {
        $this->payload = $payload;
        $this->systemUserId = (int) env('SYSTEM_USER_ID', 1);
        $this->connection = 'rabbitmq';
        $this->queue = 'processSandwichedHolidays_queue';
    }

    public function handle(): void
    {
        Log::info('ProcessSandwichedHolidaysJob started', ['payload' => $this->payload]);

        try {
            $year = $this->payload['year'] ?? null;
            $month = $this->payload['month'] ?? null;

            $employeeIds = $this->payload['employee_user_ids'] ?? null;
            if ($employeeIds !== null && !is_array($employeeIds)) {
                $employeeIds = [$employeeIds];
            }
            $employeeIds = is_array($employeeIds) ? array_values(array_filter($employeeIds)) : [];
            Log::info("Processing employees employeeIds", ['employeeIds' => $employeeIds]);

            Log::info("Processing sandwiched holidays for {$year}-{$month}");

            $monthStart = Carbon::createFromDate($year, $month, 1)->startOfDay();
            $monthEnd = $monthStart->copy()->endOfMonth();

            // Buffer window so absence/weekend chains that cross the month
            // boundary are still resolved correctly.
            $startDate = $monthStart->copy()->subDays(14);
            $endDate = $monthEnd->copy()->addDays(14);

            $employees = $this->getEmployees($employeeIds);
            Log::info("Processing employees", ['employees' => $employees]);

            if ($employees->isEmpty()) {
                Log::info('No employees found to process');
                return;
            }

            foreach ($employees as $employee) {
                $this->processEmployee($employee, $startDate, $endDate, $monthStart, $monthEnd);
            }

            Log::info('ProcessSandwichedHolidaysJob completed successfully');

        } catch (\Exception $e) {
            Log::error('ProcessSandwichedHolidaysJob failed: ' . $e->getMessage(), [
                'trace' => $e->getTraceAsString()
            ]);
            throw $e;
        }
    }

    private function getEmployees(array $employeeIds): \Illuminate\Support\Collection
    {
        $query = EmployeeOfficialInformation::whereNotNull('employee_user_id')
            ->whereNull('deleted_at')
            ->whereNull('deleted_by');

        if (!empty($employeeIds)) {
            $query->whereIn('employee_user_id', $employeeIds);
        }

        return $query->get();
    }

    private function processEmployee(
        EmployeeOfficialInformation $employee,
        Carbon $startDate,
        Carbon $endDate,
        Carbon $monthStart,
        Carbon $monthEnd
    ): void {
        $employeeUserId = $employee->employee_user_id;

        Log::debug("Processing employee {$employeeUserId} for sandwiched holidays");

        // Holidays (all types, including weekends) for this employee across the buffer window.
        $holidays = Holiday::whereBetween('date', [$startDate->toDateString(), $endDate->toDateString()])
            ->where('status', 'Active')
            ->where('employee_user_id', $employeeUserId)
            ->orderBy('date')
            ->get()
            ->keyBy('date');

        if ($holidays->isEmpty()) {
            return;
        }
        Log::info('holidays raw: ', ['holidays' => $holidays]);

        $attendance = EmployeeAttendance::with('employeeAttendanceStatusLog')
            ->where('employee_user_id', $employeeUserId)
            ->whereBetween('date', [$startDate->toDateString(), $endDate->toDateString()])
            ->get()
            ->keyBy('date');

        // Dates already resolved (deleted+recalculated) in this run, so both
        // rules see a consistent picture and we never process the same date twice.
        $resolvedDates = [];

        // Rule 1: sandwiched holiday/weekend (any type) between two absences.
        foreach ($holidays as $dateStr => $holiday) {
            $holidayDate = Carbon::parse($dateStr);
            if ($holidayDate->lt($monthStart) || $holidayDate->gt($monthEnd)) {
                continue;
            }
            if (isset($resolvedDates[$dateStr])) {
                continue;
            }

            $this->processHolidaySandwich($employee, $holiday, $holidays, $attendance, $resolvedDates);
        }

        // Rule 2: full work-week absent -> trailing weekend block absent.
        $this->processFullWeekAbsentWeekends($employee, $holidays, $attendance, $monthStart, $monthEnd, $resolvedDates);
    }

    /**
     * Rule 1: a holiday is sandwiched if the nearest non-holiday day before
     * it and the nearest non-holiday day after it (walking outward through
     * any chained holidays) are both Absent.
     */
    private function processHolidaySandwich(
        EmployeeOfficialInformation $employee,
        Holiday $holiday,
        \Illuminate\Support\Collection $holidays,
        \Illuminate\Support\Collection $attendance,
        array &$resolvedDates
    ): void {
        $employeeUserId = $employee->employee_user_id;
        $holidayDate = Carbon::parse($holiday->date);

        $previousAbsent = $this->isNearestNonHolidayDayAbsent($holidayDate, -1, $holidays, $attendance);
        $nextAbsent = $this->isNearestNonHolidayDayAbsent($holidayDate, 1, $holidays, $attendance);

        if (!($previousAbsent && $nextAbsent)) {
            return;
        }

        Log::info("Sandwiched holiday found for employee {$employeeUserId}: {$holiday->date} ({$holiday->name})");

        if ($this->wasPresent($holiday->date, $attendance)) {
            Log::info("Employee {$employeeUserId} was present on {$holiday->date}, skipping");
            return;
        }

        $this->markDateAbsent($employee, $holiday->date);
        $resolvedDates[$holiday->date] = true;
    }

    /**
     * Walk outward from $fromDate in $direction (-1 or +1) through consecutive
     * holiday dates (bounded to avoid runaway chains) until a non-holiday day
     * is reached, and report whether that day is Absent.
     */
    private function isNearestNonHolidayDayAbsent(
        Carbon $fromDate,
        int $direction,
        \Illuminate\Support\Collection $holidays,
        \Illuminate\Support\Collection $attendance
    ): bool {
        $date = $fromDate->copy();
        $maxSteps = 30;

        for ($i = 0; $i < $maxSteps; $i++) {
            $date = $date->copy()->addDays($direction);
            $dateStr = $date->toDateString();

            if ($holidays->has($dateStr)) {
                // Still inside the holiday chain, keep walking outward.
                continue;
            }

            return $this->isAbsent($dateStr, $attendance);
        }

        return false;
    }

    /**
     * Rule 2: group this employee's weekend holidays into consecutive blocks,
     * then for each block check whether every working day in the immediately
     * preceding work-week is Absent.
     */
    private function processFullWeekAbsentWeekends(
        EmployeeOfficialInformation $employee,
        \Illuminate\Support\Collection $holidays,
        \Illuminate\Support\Collection $attendance,
        Carbon $monthStart,
        Carbon $monthEnd,
        array &$resolvedDates
    ): void {
        Log::info("Processing full-week absent weekend rule for ");
        $employeeUserId = $employee->employee_user_id;
        Log::info('holidays: ', ['holidays' => $holidays]);
        $weekendDates = $holidays->filter(function ($h) {
            return (int) $h->holiday_type_id === self::WEEKEND_HOLIDAY_TYPE_ID;
        })->keys()->sort()->values();

        if ($weekendDates->isEmpty()) {
            return;
        }
        Log::info("Found weekend holidays: ", ['weekendDates' => $weekendDates->all()]);

        $weekendBlocks = $this->groupConsecutiveDates($weekendDates->all());
        Log::info("Grouped weekend blocks: ", ['weekendBlocks' => $weekendBlocks]);

        foreach ($weekendBlocks as $block) {
            $blockStart = Carbon::parse($block[0]);
            $blockEnd = Carbon::parse($block[count($block) - 1]);

            // Only act on weekend blocks that actually fall (at least partly) in the target month.
            if ($blockEnd->lt($monthStart) || $blockStart->gt($monthEnd)) {
                continue;
            }

            // Find the previous weekend/holiday block's end date, to bound the work-week.
            $weekStart = $this->findPreviousHolidayBoundary($blockStart, $holidays);

            $workingDays = $this->getWorkingDaysBetween($weekStart, $blockStart, $holidays);

            if (empty($workingDays)) {
                continue;
            }

            $allAbsent = true;
            foreach ($workingDays as $dateStr) {
                if (isset($resolvedDates[$dateStr])) {
                    continue; // already confirmed absent via rule 1 this run
                }
                if (!$this->isAbsent($dateStr, $attendance)) {
                    $allAbsent = false;
                    break;
                }
            }

            if (!$allAbsent) {
                continue;
            }

            Log::info("Full-week absence found for employee {$employeeUserId} preceding weekend block "
                . implode(',', $block));

            foreach ($block as $dateStr) {
                if (isset($resolvedDates[$dateStr])) {
                    continue;
                }
                if ($this->wasPresent($dateStr, $attendance)) {
                    Log::info("Employee {$employeeUserId} has weekend duty on {$dateStr}, skipping");
                    continue;
                }
                $this->markDateAbsent($employee, $dateStr);
                $resolvedDates[$dateStr] = true;
            }
        }
    }

    /**
     * Group a sorted list of date strings into arrays of consecutive dates.
     *
     * @param array<string> $dates
     * @return array<array<string>>
     */
    private function groupConsecutiveDates(array $dates): array
    {
        $blocks = [];
        $current = [];

        foreach ($dates as $dateStr) {
            if (empty($current)) {
                $current[] = $dateStr;
                continue;
            }

            $prev = Carbon::parse(end($current));
            if ($prev->copy()->addDay()->toDateString() === $dateStr) {
                $current[] = $dateStr;
            } else {
                $blocks[] = $current;
                $current = [$dateStr];
            }
        }

        if (!empty($current)) {
            $blocks[] = $current;
        }

        return $blocks;
    }

    /**
     * Walk backward from (blockStart - 1) to find the end of the previous
     * holiday block, returning the date right after it (exclusive lower
     * bound of the work-week). Bounded to avoid runaway loops.
     */
    private function findPreviousHolidayBoundary(Carbon $blockStart, \Illuminate\Support\Collection $holidays): Carbon
    {
        $date = $blockStart->copy()->subDay();
        $maxSteps = 60;

        for ($i = 0; $i < $maxSteps; $i++) {
            $dateStr = $date->toDateString();
            if ($holidays->has($dateStr)) {
                return $date->copy()->addDay();
            }
            $date = $date->copy()->subDay();
        }

        return $date;
    }

    /**
     * Non-holiday dates strictly between $weekStart (inclusive) and $blockStart (exclusive).
     *
     * @return array<string>
     */
    private function getWorkingDaysBetween(Carbon $weekStart, Carbon $blockStart, \Illuminate\Support\Collection $holidays): array
    {
        $days = [];
        $date = $weekStart->copy();

        while ($date->lt($blockStart)) {
            $dateStr = $date->toDateString();
            if (!$holidays->has($dateStr)) {
                $days[] = $dateStr;
            }
            $date->addDay();
        }

        return $days;
    }

    /**
     * A day is Present if its attendance row has a status-log entry with
     * attendance_status = 1 (Present). employee_attendance itself carries
     * no status column - the log is the only source of truth.
     */
    private function wasPresent(string $dateStr, \Illuminate\Support\Collection $attendance): bool
    {
        return $this->hasStatus($dateStr, $attendance, self::PRESENT_STATUS_CODE);
    }

    /**
     * A day is Absent if its attendance row has a status-log entry with
     * attendance_status = 0 (Absent).
     */
    private function isAbsent(string $dateStr, \Illuminate\Support\Collection $attendance): bool
    {
        return $this->hasStatus($dateStr, $attendance, self::ABSENT_STATUS_CODE);
    }

    private function hasStatus(string $dateStr, \Illuminate\Support\Collection $attendance, int $statusCode): bool
    {
        $record = $attendance->get($dateStr);
        if (!$record) {
            return false;
        }

        return $record->employeeAttendanceStatusLog
            ->contains(function ($log) use ($statusCode) {
                return (int) $log->attendance_status === $statusCode;
            });
    }

    /**
     * Delete the holiday row(s) for this date and write a minimal Absent
     * attendance record directly - no punch/shift recalculation involved.
     */
    private function markDateAbsent(EmployeeOfficialInformation $employee, string $dateStr): void
    {
        $employeeUserId = $employee->employee_user_id;

        DB::transaction(function () use ($employee, $employeeUserId, $dateStr) {
            $deleted = Holiday::where('date', $dateStr)
                ->where(function ($q) use ($employeeUserId) {
                    $q->whereNull('employee_user_id')
                      ->orWhere('employee_user_id', $employeeUserId);
                })
                ->delete();

            if ($deleted > 0) {
                Log::info("Deleted holiday for employee {$employeeUserId} on {$dateStr}");
            }

            $this->deleteExistingAttendance($employeeUserId, $dateStr);
            $this->insertAbsentAttendance($employee, $dateStr);
        });
    }

    private function deleteExistingAttendance(int $employeeUserId, string $date): void
    {
        $attendanceIds = EmployeeAttendance::where('employee_user_id', $employeeUserId)
            ->where('date', $date)
            ->pluck('id');

        if ($attendanceIds->isEmpty()) {
            return;
        }

        EmployeeAttendanceStatusLog::whereIn('employee_attendance_id', $attendanceIds)->delete();
        EmployeeLeaveAchieveLog::whereIn('employee_attendance_id', $attendanceIds)->delete();
        EmployeeAttendance::whereIn('id', $attendanceIds)->delete();

        Log::debug("Deleted existing attendance for employee {$employeeUserId} on {$date}");
    }

    /**
     * Look up the shift_id from the employee's most recent attendance row
     * strictly before $date, so an inserted absent day reflects the shift
     * that actually applied around that time rather than the employee's
     * current (possibly since-changed) shift assignment.
     */
    private function resolvePreviousAttendanceShiftId(int $employeeUserId, string $date): ?int
    {
        $shiftId = EmployeeAttendance::where('employee_user_id', $employeeUserId)
            ->where('date', '<', $date)
            ->whereNotNull('shift_id')
            ->orderByDesc('date')
            ->orderByDesc('id')
            ->value('shift_id');

        return $shiftId !== null ? (int) $shiftId : null;
    }

    /**
     * Insert a minimal employee_attendance row (no punches, no shift/OT
     * calculation) plus a matching Absent status-log row. absent_bridge=1
     * marks these rows as generated by the sandwich/full-week absent bridge,
     * distinct from rows produced by the normal punch-processing pipeline.
     *
     * Field set is kept 1:1 with AttendanceProcessingService::buildAttendanceRow()
     * / buildStatusLogRows() so both write paths populate the same columns.
     */
    private function insertAbsentAttendance(EmployeeOfficialInformation $employee, string $date): void
    {
        $employeeUserId = $employee->employee_user_id;
        $now = Carbon::now();
        $shiftId = $this->resolvePreviousAttendanceShiftId($employeeUserId, $date) ?? $employee->shift_id;
        $shift = $shiftId ? Shift::find($shiftId) : null;

        $attendanceId = EmployeeAttendance::insertGetId([
            'emp_code'                                  => $employee->emp_code ?? null,
            'employee_user_id'                          => $employeeUserId,
            'department_id'                              => $employee->department_id,
            'section_id'                                 => $employee->section_id,
            'shift_id'                                   => $shiftId,
            'leave_id'                                   => null,
            'shift_start_time'                           => $shift->clock_in ?? '09:00:00',
            'shift_grace_time'                           => $shift->shift_grace_time ?? 0,
            'shift_end_time'                             => $shift->clock_out ?? '18:00:00',
            'date'                                       => $date,
            'in_time'                                    => null,
            'out_date'                                   => null,
            'out_time'                                   => null,
            'on_leave_status'                            => null,
            'transfered_to_ot'                           => 0,
            'is_holiday'                                 => 0,
            'is_join'                                    => 0,
            'is_manual'                                  => 1,
            'is_roster'                                  => 0,
            'roster_id'                                  => null,
            'absent_bridge'                               => 1,
            'source'                                      => 'manual',
            'is_corrected'                                => 0,
            'working_hours'                               => 0,
            'employee_applied_attendance_correction_id'  => null,
            'created_user_id'                            => $this->systemUserId,
            'updated_user_id'                            => $this->systemUserId,
            'deleted_user_id'                            => null,
            'created_at'                                 => $now,
            'remarks'                                    => 'Marked absent by sandwiched-holiday/full-week-absent bridge job',
        ]);

        EmployeeAttendanceStatusLog::insert([
            'employee_user_id'       => $employeeUserId,
            'employee_attendance_id' => $attendanceId,
            'leave_application_id'   => null,
            'attendance_status'      => self::ABSENT_STATUS_CODE,
            'attendance_date'        => $date,
            'created_user_id'        => $this->systemUserId,
            'created_at'             => $now,
        ]);

        Log::info("Marked employee {$employeeUserId} absent on {$date}, attendance ID: {$attendanceId}");
    }
}
